spring:
  datasource:
    url: jdbc:h2:mem:testdb;NON_KEYWORDS=USER
  h2:
    console:
      enabled: true
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true #do not implement for production !
    show-sql: true

logging:
  level:
    org:
      hibernate:
        stat: debug
        type: trace